### ISSUE TITLE
"Create a Function with a Docker Container" link/page should be removed

### ISSUE THREAD

**Issue by rikgibson** [fnproject/tutorials#131]
This is not currently supported now so should be removed.  If/when we support something similar/equivalent it will be done differently.

**Comment by rdallman** [comment]
this isn't true, it's just now we require an fdk to be used or users to write code to handle the http-over-uds protocol. as far as I can tell, the page simply needs updating to include an fdk for i/o to enclose the provided example instead of reading from stdin/stdout, but it's still possible to build a docker container with a `Dockerfile` and run it on fn.

**Comment by michael-w-williams** [comment]
Fixed in PR: https://github.com/fnproject/tutorials/pull/143
