### ISSUE TITLE
Introduction to Java Fn , fn run need authentication.

### ISSUE THREAD

**Issue by xhusky** [fnproject/tutorials#4]
$ export FN_REGISTRY=fndemouser
$ fn run
Building image fndemouser/javafn:0.0.1
Sending build context to Docker daemon  13.82kB
Step 1/11 : FROM fnproject/fn-java-fdk-build:latest as build-stage
Get https://registry-1.docker.io/v2/fnproject/fn-java-fdk-build/manifests/latest: unauthorized: incorrect username or password
ERROR: error running docker build: exit status 1

**Comment by rdallman** [comment]
Hi @xhusky 

it's likely that your docker credentials are wrong on your machine, as this image is public and privileges are open. have seen this with a couple of users working through the tutorial and the fix was generally that credentials were wrong under `~/.docker/config.json` or `~/.dockercfg`, all that's going on in this command is attempting to pull a build image to package up the code in so that it can be run. thanks for helping test!

**Comment by xhusky** [comment]
@rdallman thank you very much. my problem is solved. because my docker is not logged in. run `docker login` solved it.
